services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=elasticuser
      - ELASTICSEARCH_PASSWORD=elasticpw
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elasticuser
      - ELASTICSEARCH_PASSWORD=elasticpw
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.1
    container_name: logstash
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elasticuser
      - ELASTICSEARCH_PASSWORD=elasticpw
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpw
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=zaq1@WSX
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  rabbitmq_data:
  pgdata:
  esdata: